**Stacking - İstifleme**

In [1]:
import numpy as np

In [4]:
dizi1 = np.array([[1,2],[3,4]])
dizi1

array([[1, 2],
       [3, 4]])

In [5]:
dizi2 = np.array([[-1,-2],[-3,-4]])
dizi2

array([[-1, -2],
       [-3, -4]])

In [8]:
dizi_dikey = np.vstack((dizi1,dizi2))
dizi_dikey

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]])

In [9]:
dizi_yatay = np.hstack((dizi1,dizi2))
dizi_yatay

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

In [11]:
#problem 2 boyutlu 2 satır ve 2 sütün olan 3 adet array oluştur,
#bunları yatayda ve dikeyde birleştir.

In [14]:
dizi3 = np.array([[1,3],[4,6]])
dizi3

array([[1, 3],
       [4, 6]])

In [15]:
dizi_dikey_uclu = np.vstack((dizi1,dizi2,dizi3))
dizi_dikey_uclu

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4],
       [ 1,  3],
       [ 4,  6]])

In [16]:
dizi_yatay_uclu = np.hstack((dizi1,dizi2,dizi3))
dizi_yatay_uclu

array([[ 1,  2, -1, -2,  1,  3],
       [ 3,  4, -3, -4,  4,  6]])

**PANDAS**

*   .csc, .txt bunların okunması ve import edilmesi için
*   Preprocessing: verinin training için hazır hale getirilmesi
*   EDA (Kesifsel Veri Analizi): outlier tespiti, feature extration, correlation....



In [17]:
import pandas as pd

**Dataframe Kavramı**

In [19]:
#dataframe
dictinoary = {"isim": ["ali", "veli", "kenan", "murat", "ayse", "hilal"],
              "yas": [15, 16, 17, 33, 45, 66],
              "maas": [100.0, 150.0, 240.0, 350.0, 110.0, 220.0]}

dictinoary

{'isim': ['ali', 'veli', 'kenan', 'murat', 'ayse', 'hilal'],
 'yas': [15, 16, 17, 33, 45, 66],
 'maas': [100, 150, 240, 350, 110, 220]}

In [28]:
veri = pd.DataFrame(dictinoary) # dataframe = pandas degisken tipi
print(type(veri))
veri


<class 'pandas.core.frame.DataFrame'>


isim  yas  maas
0    ali   15   100
1   veli   16   150
2  kenan   17   240
3  murat   33   350
4   ayse   45   110
5  hilal   66   220

In [27]:
veri.head() # ilk 5 satır

isim  yas  maas
0    ali   15   100
1   veli   16   150
2  kenan   17   240
3  murat   33   350
4   ayse   45   110

In [29]:
veri.tail() # son 5 satır

isim  yas  maas
1   veli   16   150
2  kenan   17   240
3  murat   33   350
4   ayse   45   110
5  hilal   66   220

In [30]:
veri.columns # veri sütunlarının adları

Index(['isim', 'yas', 'maas'], dtype='object')

In [32]:
# dataframe ile ilgili temel bilgilere ulaşmamız lazım
veri.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   isim    6 non-null      object
 1   yas     6 non-null      int64 
 2   maas    6 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 272.0+ bytes


In [33]:
veri.describe() # Veride bulunan numarik(sayısal) feature'ların(sütunların) temel istatistikleri

yas        maas
count   6.000000    6.000000
mean   32.000000  195.000000
std    20.474374   94.815611
min    15.000000  100.000000
25%    16.250000  120.000000
50%    25.000000  185.000000
75%    42.000000  235.000000
max    66.000000  350.000000

In [35]:
dictinoary2 = {"Calisan_adi": ["ali", "veli", "kenan", "murat", "ayse", "hilal"],
              "Calisan_yas": [15, 16, 17, 33, 45, 85],
               "Sigorta_durum":[0,1,1,0,1,0]}

dictinoary2

{'Calisan_adi': ['ali', 'veli', 'kenan', 'murat', 'ayse', 'hilal'],
 'Calisan_yas': [15, 16, 17, 33, 45, 85],
 'Sigorta_durum': [0, 1, 1, 0, 1, 0]}

In [38]:
veri2 = pd.DataFrame(dictinoary2)
veri2


Calisan_adi  Calisan_yas  Sigorta_durum
0         ali           15              0
1        veli           16              1
2       kenan           17              1
3       murat           33              0
4        ayse           45              1
5       hilal           85              0

In [44]:
veri2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Calisan_adi    6 non-null      object
 1   Calisan_yas    6 non-null      int64 
 2   Sigorta_durum  6 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 272.0+ bytes


In [41]:
veri2.columns

Index(['Calisan_adi', 'Calisan_yas', 'Sigorta_durum'], dtype='object')

In [42]:
veri2.tail()

Calisan_adi  Calisan_yas  Sigorta_durum
1        veli           16              1
2       kenan           17              1
3       murat           33              0
4        ayse           45              1
5       hilal           85              0

In [43]:
veri2.head()

Calisan_adi  Calisan_yas  Sigorta_durum
0         ali           15              0
1        veli           16              1
2       kenan           17              1
3       murat           33              0
4        ayse           45              1

In [45]:
veri2.describe()

Calisan_yas  Sigorta_durum
count     6.000000       6.000000
mean     35.166667       0.500000
std      27.161861       0.547723
min      15.000000       0.000000
25%      16.250000       0.000000
50%      25.000000       0.500000
75%      42.000000       1.000000
max      85.000000       1.000000

In [46]:
print(veri2)

  Calisan_adi  Calisan_yas  Sigorta_durum
0         ali           15              0
1        veli           16              1
2       kenan           17              1
3       murat           33              0
4        ayse           45              1
5       hilal           85              0


**İndeksleme ve Dilimleme**

In [51]:
dictinoary = {"isim": ["ali", "veli", "kenan", "murat", "ayse", "hilal"],
              "yas": [15, 16, 17, 33, 45, 66],
              "maas": [100.0, 150.0, 240.0, 350.0, 110.0, 220.0]}
dictinoary

veri = pd.DataFrame(dictinoary)
veri

isim  yas   maas
0    ali   15  100.0
1   veli   16  150.0
2  kenan   17  240.0
3  murat   33  350.0
4   ayse   45  110.0
5  hilal   66  220.0

In [49]:
veri["yas"]

0    15
1    16
2    17
3    33
4    45
5    66
Name: yas, dtype: int64

In [53]:
veri["maas"]

0    100.0
1    150.0
2    240.0
3    350.0
4    110.0
5    220.0
Name: maas, dtype: float64

In [55]:
# dataframe icerisine yeni sutun ekleme
veri["sehir"] = ["istanbul", "ankara", "izmir", "bursa", "izmir", "istanbul"]
veri

isim  yas   maas     sehir
0    ali   15  100.0  istanbul
1   veli   16  150.0    ankara
2  kenan   17  240.0     izmir
3  murat   33  350.0     bursa
4   ayse   45  110.0     izmir
5  hilal   66  220.0  istanbul

In [57]:
veri["maas_yuzde_20_zamli"] = veri["maas"] + 20*veri["maas"]/100
veri

isim  yas   maas     sehir  maas_yuzde_20_zamli
0    ali   15  100.0  istanbul                120.0
1   veli   16  150.0    ankara                180.0
2  kenan   17  240.0     izmir                288.0
3  murat   33  350.0     bursa                420.0
4   ayse   45  110.0     izmir                132.0
5  hilal   66  220.0  istanbul                264.0

In [59]:
# veri["yas"]
# loc = location kisaltma
veri.loc[:, "yas"] # row=satirlar, column = sutunlar

0    15
1    16
2    17
3    33
4    45
5    66
Name: yas, dtype: int64

In [61]:
veri.loc[0:2, "yas"]

0    15
1    16
2    17
Name: yas, dtype: int64

In [62]:
veri.columns

Index(['isim', 'yas', 'maas', 'sehir', 'maas_yuzde_20_zamli'], dtype='object')

In [63]:
veri.loc[0:2, ["isim", "maas", "sehir"]]

isim   maas     sehir
0    ali  100.0  istanbul
1   veli  150.0    ankara
2  kenan  240.0     izmir

In [64]:
veri.loc[0:2, 'isim':'sehir']

isim  yas   maas     sehir
0    ali   15  100.0  istanbul
1   veli   16  150.0    ankara
2  kenan   17  240.0     izmir

In [65]:
veri.iloc[0:2,1]

0    15
1    16
Name: yas, dtype: int64

In [66]:
veri.iloc[[2,4], [1,2]]

yas   maas
2   17  240.0
4   45  110.0

In [67]:
veri["maas2"] = veri["maas"] + 10
veri

isim  yas   maas     sehir  maas_yuzde_20_zamli  maas2
0    ali   15  100.0  istanbul                120.0  110.0
1   veli   16  150.0    ankara                180.0  160.0
2  kenan   17  240.0     izmir                288.0  250.0
3  murat   33  350.0     bursa                420.0  360.0
4   ayse   45  110.0     izmir                132.0  120.0
5  hilal   66  220.0  istanbul                264.0  230.0

In [68]:
cols = veri.columns.tolist()
cols

['isim', 'yas', 'maas', 'sehir', 'maas_yuzde_20_zamli', 'maas2']

In [69]:
maas2_index = cols.index('maas2')
maas2_index

5

In [70]:
cols.remove('maas2')
cols

['isim', 'yas', 'maas', 'sehir', 'maas_yuzde_20_zamli']

In [71]:
cols.insert(1, 'maas2')  # maas2'yi yas'tan sonra ekleyin (index 2)


In [72]:
cols

['isim', 'maas2', 'yas', 'maas', 'sehir', 'maas_yuzde_20_zamli']

In [73]:
veri = veri[cols]

In [74]:
veri

isim  maas2  yas   maas     sehir  maas_yuzde_20_zamli
0    ali  110.0   15  100.0  istanbul                120.0
1   veli  160.0   16  150.0    ankara                180.0
2  kenan  250.0   17  240.0     izmir                288.0
3  murat  360.0   33  350.0     bursa                420.0
4   ayse  120.0   45  110.0     izmir                132.0
5  hilal  230.0   66  220.0  istanbul                264.0

In [75]:
dictinoary = {"isim": ["ali", "veli", "kenan", "murat", "ayse", "hilal"],
              "yas": [15, 16, 17, 33, 45, 66],
              "maas": [100.0, 150.0, 240.0, 350.0, 110.0, 220.0]}
dictinoary

veri = pd.DataFrame(dictinoary)
veri

isim  yas   maas
0    ali   15  100.0
1   veli   16  150.0
2  kenan   17  240.0
3  murat   33  350.0
4   ayse   45  110.0
5  hilal   66  220.0

In [76]:
"""
1) Murat 33
2) 45 110
  66 220
3) veli 45
"""

'\n1) Murat 33\n2) 45 110\n  66 220\n3) veli 45\n'

In [85]:
veri.loc[3, ["isim","yas"]]

isim    murat
yas        33
Name: 3, dtype: object

In [88]:
veri.loc[4:5, ["yas","maas"]]

yas   maas
4   45  110.0
5   66  220.0

In [91]:
# Iloc ile
print(veri.iloc[3, 0:2]) # 1.sorunun cevabı.
print(veri.iloc[4:6, 1:3]) # 2.sorunun cevabı.
print(veri.iloc[1, 0], veri.iloc[4, 1]) # 3.Sorunun cevabı

print(veri.loc[3, "isim":"yas"]) # 1.sorunun cevabı.
print(veri.loc[4:6, "yas":"maas"]) # 2.sorunun cevabı.
print(veri.loc[1, "isim"], veri.loc[4, "yas"]) # 3.Sorunun cevabı

isim    murat
yas        33
Name: 3, dtype: object
   yas   maas
4   45  110.0
5   66  220.0
veli 45
isim    murat
yas        33
Name: 3, dtype: object
   yas   maas
4   45  110.0
5   66  220.0
veli 45


**Filtreleme**

In [92]:
dictinoary = {"isim": ["ali", "veli", "kenan", "murat", "ayse", "hilal"],
              "yas": [15, 16, 17, 33, 45, 66],
              "sehir": ["izmir","ankara","konya","ankara","ankara","antalya"]}
dictinoary

veri = pd.DataFrame(dictinoary)
veri

isim  yas    sehir
0    ali   15    izmir
1   veli   16   ankara
2  kenan   17    konya
3  murat   33   ankara
4   ayse   45   ankara
5  hilal   66  antalya

In [95]:
filtre1 = veri["yas"] > 22
filtre1

0    False
1    False
2    False
3     True
4     True
5     True
Name: yas, dtype: bool

In [96]:
filtrelenmis_veri = veri[filtre1]
filtrelenmis_veri

isim  yas    sehir
3  murat   33   ankara
4   ayse   45   ankara
5  hilal   66  antalya

In [98]:
filtre2 = veri["sehir"] == "ankara"
veri[filtre2]

isim  yas   sehir
1   veli   16  ankara
3  murat   33  ankara
4   ayse   45  ankara

In [99]:
veri[filtre1 & filtre2]

isim  yas   sehir
3  murat   33  ankara
4   ayse   45  ankara

In [100]:
veri

isim  yas    sehir
0    ali   15    izmir
1   veli   16   ankara
2  kenan   17    konya
3  murat   33   ankara
4   ayse   45   ankara
5  hilal   66  antalya

In [102]:
# veri.isim
filtre3 = veri["isim"] == "ali"
veri[filtre3]

isim  yas  sehir
0  ali   15  izmir

In [103]:
np.bitwise_and(veri["yas"] > 22, veri["sehir"] == "ankara")

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [104]:
#filtre4 = veri["isim"] == "ali"
#veri[filtre4]
veri[veri["isim"] == "ali"]

isim  yas  sehir
0  ali   15  izmir

In [105]:
filtered_veri = veri.loc[(veri["sehir"] == "ankara") & (veri["yas"] > 22)]
print(filtered_veri)

    isim  yas   sehir
3  murat   33  ankara
4   ayse   45  ankara


In [108]:
dictionary = {"isim": ["ali", "veli", "kenan", "murat", "ayse", "hilal"],
              "yas": [15, 16, 17, 33, 45 , 66],
              "sehir": ["izmir", "ankara", "konya", "ankara", "ankara","antalya"]}
veri=pd.DataFrame(dictionary)
veri
"""
1) yeni sutun: maas sutunu ekle
2) yeni sutun: yas/maas orani sutunu ekle
3) yas/maas sutunu icin ortalamayi print ettir
4) ankarada yasayanlarin ortalama yasini bul
5) ankarada yasayanlarin icinden en yuksek maas alani bul
"""

'\n1) yeni sutun: maas sutunu ekle\n2) yeni sutun: yas/maas orani sutunu ekle\n3) yas/maas sutunu icin ortalamayi print ettir\n4) ankarada yasayanlarin ortalama yasini bul\n5) ankarada yasayanlarin icinden en yuksek maas alani bul\n'

In [109]:
veri

isim  yas    sehir
0    ali   15    izmir
1   veli   16   ankara
2  kenan   17    konya
3  murat   33   ankara
4   ayse   45   ankara
5  hilal   66  antalya

In [110]:
veri["maas"] = [100,200,300,400,500,600]
veri

isim  yas    sehir  maas
0    ali   15    izmir   100
1   veli   16   ankara   200
2  kenan   17    konya   300
3  murat   33   ankara   400
4   ayse   45   ankara   500
5  hilal   66  antalya   600

In [111]:
veri["yas_maas"] = veri["yas"] / veri["maas"]
veri

isim  yas    sehir  maas  yas_maas
0    ali   15    izmir   100  0.150000
1   veli   16   ankara   200  0.080000
2  kenan   17    konya   300  0.056667
3  murat   33   ankara   400  0.082500
4   ayse   45   ankara   500  0.090000
5  hilal   66  antalya   600  0.110000

In [112]:
np.mean(veri["yas_maas"])

0.0948611111111111

In [107]:
veri["ulke"] = ["turkiye"]*len(veri)
veri

isim  yas    sehir     ulke
0    ali   15    izmir  turkiye
1   veli   16   ankara  turkiye
2  kenan   17    konya  turkiye
3  murat   33   ankara  turkiye
4   ayse   45   ankara  turkiye
5  hilal   66  antalya  turkiye

In [113]:
# 4) ankarada yasayanlarin ortalama yasini bul
ankarada_yasayanlar = veri[veri["sehir"] == "ankara"]
ankarada_yasayanlar

isim  yas   sehir  maas  yas_maas
1   veli   16  ankara   200    0.0800
3  murat   33  ankara   400    0.0825
4   ayse   45  ankara   500    0.0900

In [114]:
# 4) ankarada yasayanlarin ortalama yasini bul
ankarada_yasayanlar_yas = ankarada_yasayanlar["yas"]
ankarada_yasayanlar_yas

1    16
3    33
4    45
Name: yas, dtype: int64

In [115]:
# 4) ankarada yasayanlarin ortalama yasini bul
ort = np.mean(ankarada_yasayanlar_yas)
ort

31.333333333333332

In [116]:
# 5) ankarada yasayanlarin icinden en yuksek maas alani bul
ankarada_yasayanlar = veri[veri["sehir"] == "ankara"]
ankarada_yasayanlar

isim  yas   sehir  maas  yas_maas
1   veli   16  ankara   200    0.0800
3  murat   33  ankara   400    0.0825
4   ayse   45  ankara   500    0.0900

In [117]:
# 5) ankarada yasayanlarin icinden en yuksek maas alani bul
ankarada_yasayanlar_maas = ankarada_yasayanlar["maas"]
ankarada_yasayanlar_maas

1    200
3    400
4    500
Name: maas, dtype: int64

In [118]:
# 5) ankarada yasayanlarin icinden en yuksek maas alani bul

np.max(ankarada_yasayanlar_maas)

500

In [123]:
# maximum maasi alanin adini bulalim
ankarada_yasayanlar

isim  yas   sehir  maas  yas_maas
1   veli   16  ankara   200    0.0800
3  murat   33  ankara   400    0.0825
4   ayse   45  ankara   500    0.0900

In [120]:
dictionary = {"isim":["ali","veli","kenan", "murat","ayşe","hilal"],
              "yas" : [15,16,17,33,45,66],
              "sehir": ["İzmir", "Ankara", "Konya", "Ankara", "Ankara", "Antalya"]}
veri=pd.DataFrame(dictionary)
veri

isim  yas    sehir
0    ali   15    İzmir
1   veli   16   Ankara
2  kenan   17    Konya
3  murat   33   Ankara
4   ayşe   45   Ankara
5  hilal   66  Antalya

In [121]:
veri[veri["sehir"]=="Ankara"]["yas"].mean()

31.333333333333332

In [122]:
"""
for dongusu kullanarak maximum maas alanin ismini bulalim
"""

'\nfor dongusu kullanarak maximum maas alanin ismini bulalim\n'

In [126]:
ankarada_yasayanlar.reset_index(drop=True, inplace=True)
ankarada_yasayanlar

isim  yas   sehir  maas  yas_maas
0   veli   16  ankara   200    0.0800
1  murat   33  ankara   400    0.0825
2   ayse   45  ankara   500    0.0900

In [129]:
maks_maas = 0
maks_isim = ""
for i in range(len(ankarada_yasayanlar)):
    if ankarada_yasayanlar["maas"][i] > maks_maas:
        maks_maas = ankarada_yasayanlar["maas"][i]
        maks_isim = ankarada_yasayanlar["isim"][i]

print(maks_isim)

ayse


In [130]:
ankarada_yasayanlar.loc[ankarada_yasayanlar["maas"].idxmax(), "isim"]

'ayse'