In [ ]:
# bu benim ilk commentim degil (:
# degisken - variable
# integer(tamsayi) degisken - variable
tamsayi_degiskeni = 10 # 10 tamsayisi için bir degisken tanımladım, bu degiskenin ismi tamsayi_degiskeni
tamsayi_degiskeni2 = 15
print(tamsayi_degiskeni)
print(tamsayi_degiskeni2)


10
15


**Kesirli Sayi**

In [ ]:
# kesirli sayi - float
kesirlisayi_degisken = 10.5
print(kesirlisayi_degisken)


10.5


Dört İşlem Özelliği

In [ ]:
toplam = tamsayi_degiskeni + tamsayi_degiskeni2
cikarma = tamsayi_degiskeni - tamsayi_degiskeni2
carpma = tamsayi_degiskeni * tamsayi_degiskeni2
bolme = tamsayi_degiskeni / tamsayi_degiskeni2
print(toplam)
print(cikarma)
print(carpma)
print(bolme)

25
-5
150
0.6666666666666666


In [ ]:
metin = "Merhaba Dunya" # string - metin
print(metin)

Merhaba Dunya


In [ ]:
type(metin)

str

In [ ]:
metin1 = "Merhaba"
bosluk = " "
metin2 = "Dunya"
metin1 + bosluk + metin2

'Merhaba Dunya'

In [ ]:
# f string
# elma -> 10₺
# armut -> 20₺
elma_degisken = 10
armut_degisken = 20
print(f"elma: {elma_degisken}₺, armut: {armut_degisken}₺")
print("elma: 10₺, armut: 20₺")
f"{metin1} {bosluk} {metin2}"

elma: 10₺, armut: 20₺
elma: 10₺, armut: 20₺


'Merhaba   Dunya'

Python Syntax

In [ ]:
temel = 6
TEMEL = 7
print(temel)
print(TEMEL)

6
7


In [ ]:
# COMMENT
"""
Geniş paragraf açıklamalarınızı bu şekilde yapabilirsiniz.
"""

'\nGeniş paragraf açıklamalarınızı bu şekilde yapabilirsiniz.\n'

In [ ]:
print(5)

5


In [ ]:
# print = 10

In [ ]:
print(5)

5


**Fonksiyonlar**



*   Kullanıcı Tanımlı Fonksiyonlar (User Defined Function)



In [ ]:
# dairenin alanını hesaplamak pi*r^2
pi = 3.14
daire_yaricapi = 3
daire_alani = pi * (daire_yaricapi ** 2)
print(daire_alani)


28.26


In [ ]:
def daireAlaniHesapla(): # func ismi yazarken islevi belirtmek lazim
  pi = 3.14
  daire_yaricapi = 3
  daire_alani = pi * (daire_yaricapi ** 2)
  print(daire_alani)

In [ ]:
daireAlaniHesapla()

Daire Alani Hesapla:


In [ ]:
def AdSoyad():
  print("Atakan Erdoğan")

AdSoyad()

Atakan Erdoğan


In [ ]:
def daireAlaniHesapla(daire_yaricapi = 5): # func ismi yazarken islevi belirtmek lazim
  """
    Defination: Bu fonksiyon dairenin alanini hesaplar.
    input parameters: degisken yaricapi (daire_yaricapi)
    output: dairenin alani (daire_alani)
  """
  PI = 3.14 # değişmeyecek değişkenlerin adları büyük harflerle yazılır
  daire_alani = PI * (daire_yaricapi ** 2)
  print(f"Daire alani: {daire_alani}")
  return daire_alani

In [ ]:
daireAlaniHesapla(3)

Daire_alani: 28.26


In [ ]:
user_input = input("Lütfen bir daire yari capi giriniz: ")
print(f"girilen değer: {user_input} ve bu degerin tipi: {type(user_input)}")
user_input = int(user_input)
print(f"girilen değer: {user_input} ve bu degerin tipi: {type(user_input)}")
daireAlaniHesapla(user_input)

Lütfen bir daire yari capi giriniz: 10
girilen değer: 10 ve bu degerin tipi: <class 'str'>
girilen değer: 10 ve bu degerin tipi: <class 'int'>
Daire alani: 314.0


In [ ]:
daire_alani_hesaplanan1 = daireAlaniHesapla(5)
daire_alani_hesaplanan2 = daireAlaniHesapla(3)
print(daire_alani_hesaplanan1 + daire_alani_hesaplanan2)

Daire alani: 78.5
Daire alani: 28.26
106.76


In [ ]:
# daire cevresi hesaplama: 2*pi*r

def daireCevresiHesapla(r):
  PI = 3.14
  daireCevre = 2 * PI * r
  print(f"Daire cevresi: {daireCevre}")
  return daireCevre

In [ ]:
daireCevresiHesapla(2)

Daire cevresi: 12.56


12.56

In [ ]:
user_input = input("Lütfen bir daire çevresini giriniz: ")
print(f"girilen değer: {user_input} ve bu degerin tipi: {type(user_input)}")
user_input = int(user_input)
daireCevresiHesapla(user_input)

14.12.2024

Veri Tipleri: Liste

In [2]:
liste = ["süt", "yumurta", "ekmek"]
liste

['süt', 'yumurta', 'ekmek']

In [4]:
liste_fiyat = [10, 20, 30]
print(liste_fiyat)

[10, 20, 30]


In [6]:
type(liste_fiyat)

list

In [8]:
hafta_liste = ["pazartesi", "sali", "carsamba", "persembe", "cuma", "cumartesi", "pazar"]
print(hafta_liste)

['pazartesi', 'sali', 'carsamba', 'persembe', 'cuma', 'cumartesi', 'pazar']


In [9]:
# İndeksleme
hafta_liste[0] # 0. indeksteki eleman

'pazartesi'

In [11]:
len(hafta_liste) # listedeki eleman sayısı

7

In [10]:
# İndeksleme
hafta_liste[3] # 3. indeksteki eleman

'persembe'

In [13]:
# İndeksleme
hafta_liste[len(hafta_liste)-1] # 3. indeksteki eleman

'pazar'

In [14]:
hafta_liste[-1] # son eleman

'pazar'

In [15]:
hafta_liste = ["pazartesi", "sali", "carsamba", "persembe", "cuma", "cumartesi", "pazar"]
# "pazartesi", "sali", "carsamba", "persembe"
hafta_liste[0:4]

['pazartesi', 'sali', 'carsamba', 'persembe']

In [16]:
# "persembe", "cuma", "cumartesi", "pazar"
print(hafta_liste[3:])
print(hafta_liste[3:8])
print(hafta_liste[-4:])


['persembe', 'cuma', 'cumartesi', 'pazar']
['persembe', 'cuma', 'cumartesi', 'pazar']
['persembe', 'cuma', 'cumartesi', 'pazar']


In [17]:
sayi_listesi = [1,3,2,4,6,5]
sayi_listesi

[1, 3, 2, 4, 6, 5]

In [19]:
sayi_listesi.append(7) # listenin sonuna eleman ekler
sayi_listesi

[1, 3, 2, 4, 6, 5, 7, 7]

In [27]:
sayi_listesi.remove(4) # listenin eleman siler
sayi_listesi

[1, 3, 2, 7, 7]

In [29]:
sayi_listesi.reverse() # listenin ters çevir
sayi_listesi

[7, 7, 2, 3, 1]

In [30]:
sayi_listesi.sort() # listenin küçükten büyüğe sıralanması
sayi_listesi

[1, 2, 3, 7, 7]

In [39]:
liste_deneme = [1,3,2,4,6,5]
liste_deneme_sorted = sorted(liste_deneme) # listenin büyükten küçüğe sıralanması
print(liste_deneme)
print(liste_deneme_sorted)

[1, 3, 2, 4, 6, 5]
[1, 2, 3, 4, 5, 6]


Veri Tipleri: Tuple

In [36]:
tuple_sayi = (1,2,3,3,4,5,6)
print(tuple_sayi[-2])
print(tuple_sayi[1])
print(tuple_sayi[2:])
print(tuple_sayi.count(3))

5
2
(3, 3, 4, 5, 6)
2


Veri Tipleri: Dictionary
  *   anahtar - değer : key-value pair




In [40]:
dictionary = {"anahatar": 10,
              "key": "ankara"}
dictionary

{'anahatar': 10, 'key': 'ankara'}

In [42]:
sehirler_plakalar = {"istanbul": 34,
                     "izmir": 35,
                     "konya": 42
                     }

sehirler_plakalar

{'istanbul': 34, 'izmir': 35, 'konya': 42}

In [44]:
sehirler_plakalar.keys()

dict_keys(['istanbul', 'izmir', 'konya'])

In [45]:
sehirler_plakalar.values()

dict_values([34, 35, 42])

In [46]:
sehirler_plakalar["izmir"]

35

Veri Tipleri Dönüşümleri

In [47]:
metin = "16"
kesirlisayi = 10.5
tamsayi = 10
print(type(metin))
print(type(kesirlisayi))
print(type(tamsayi))

<class 'str'>
<class 'float'>
<class 'int'>


In [50]:
# str -> int
metin_int = int(metin)
print((metin_int))
print(type(metin_int))

16
<class 'int'>


In [52]:
# float -> int
kesirlisayi_int = int(10.6)
print(kesirlisayi_int)
print(type(kesirlisayi_int))

10
<class 'int'>


In [54]:
# float -> str
kesirlisayi_str = str(kesirlisayi)
print(kesirlisayi_str)
print(type(kesirlisayi_str))

10.5
<class 'str'>


In [56]:
# int -> str
tamsayi_str = str(tamsayi)
print(tamsayi_str)
print(type(tamsayi_str))

10
<class 'str'>


In [58]:
# int -> float
tamsayi_float = float(tamsayi)
print(tamsayi_float)
print(type(tamsayi_float))

10.0
<class 'float'>


if-else

In [73]:
# eüer sayi1 küçüktür sayi2 ise print(sayi1 küçüktür sayi2)
sayi1 = 12
sayi2 = 12

if sayi1 < sayi2: # Eğer True(Doğru) ise if içerisine gir
  print(f"sayi1:{sayi1} küçüktür sayi2: {sayi2}")
elif sayi2 < sayi1: # Eğer True(Doğru) ise if içerisine gir
  print(f"sayi2:{sayi2} küçüktür sayi1: {sayi1}")
elif sayi1 == sayi2: # Eğer True(Doğru) ise if içerisine gir
  print(f"sayi1:{sayi1} sayi2: {sayi2} eşittir")

sayi1:12 sayi2: 12 eşittir


'\n# eüer sayi1 küçüktür sayi2 ise print(sayi1 küçüktür sayi2)\nsayi1 = 12\nsayi2 = 12\n\nif sayi1 < sayi2: # Eğer True(Doğru) ise if içerisine gir\n  print(f"sayi1:{sayi1} küçüktür sayi2: {sayi2}")\nelif sayi2 < sayi1: # Eğer True(Doğru) ise if içerisine gir\n  print(f"sayi2:{sayi2} küçüktür sayi1: {sayi1}")\nelse: # Eğer True(Doğru) ise if içerisine gir\n  print(f"sayi1:{sayi1} sayi2: {sayi2} eşittir")\n'

In [60]:
sayi1 < sayi2

True

In [74]:
# eüer sayi1 küçüktür sayi2 ise print(sayi1 küçüktür sayi2)
sayi1 = 12
sayi2 = 12

if sayi1 < sayi2: # Eğer True(Doğru) ise if içerisine gir
  print(f"sayi1:{sayi1} küçüktür sayi2: {sayi2}")
elif sayi2 < sayi1: # Eğer True(Doğru) ise if içerisine gir
  print(f"sayi2:{sayi2} küçüktür sayi1: {sayi1}")
else: # Eğer True(Doğru) ise if içerisine gir
  print(f"sayi1:{sayi1} sayi2: {sayi2} eşittir")

sayi1:12 sayi2: 12 eşittir


In [78]:
# problem: değer listenin içerisinde mi değil mi?
liste = [1,2,3,4,5]
deger = 10

if deger in liste:
  print(f"{deger} listenin içerisinde")
else:
  print(f"{deger} listenin içerisinde değil")

10 listenin içerisinde değil


In [80]:
dictionary = {"Türkiye": "Ankara",
              "İngiltere": "Londra",
              "Fransa": "Paris",
              "Almanya": "Berlin"
              }

keys = dictionary.keys()
print(keys)
print(type(keys))

dict_keys(['Türkiye', 'İngiltere', 'Fransa', 'Almanya'])
<class 'dict_keys'>


In [83]:
#deger = "Türkiye"
deger = "İspanya"

if deger in keys:
  print(f"{deger} dictionary içerisinde")
else:
  print(f"{deger} dictionary içerisinde değil")
#

İspanya dictionary içerisinde değil


In [86]:
# liste = haftanın günleri
# eger pazartesi günü listenin içerisinde 2. indexde ise print(pazartesi günü listenin ikinci indeksinde)

liste = ["pazartesi", "sali", "carsamba", "persembe", "cuma", "cumartesi", "pazar"]
if "pazartesi" in liste[2]:
  print(f"pazartesi günü listenin {liste.index('pazartesi')}. indexinde")
else:
  print(f"pazartesi günü listenin ikinci indexinde değil")

pazartesi günü listenin ikinci indexinde değil


for loop

In [88]:
# 1'den 10'a kadar saydır
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [89]:
for i in [1,2,3,4,5]:
  print(i*2)

2
4
6
8
10


In [93]:
for i in ["pazartesi", "sali", "carsamba", "persembe", "cuma", "cumartesi", "pazar"]: # string = karakter dizisi
  print(i)

pazartesi
sali
carsamba
persembe
cuma
cumartesi
pazar


In [94]:
liste1 = ["pazartesi", "sali", "carsamba", "persembe", "cuma", "cumartesi", "pazar"]

for i in liste1: # string = karakter dizisi
  print(i)

pazartesi
sali
carsamba
persembe
cuma
cumartesi
pazar


In [95]:
for i in "Pazartesi Sali":
  print(i)

P
a
z
a
r
t
e
s
i
 
S
a
l
i


In [102]:
liste = [1,2,3,4,5,6,7,8,9]
toplam = 0

for i in liste:
  toplam = toplam + i
print(toplam)

print(sum(liste))

45
45


In [104]:
"""
problem: NLP, elimizde str olarak cümle var,
ornek: "Bugün Python Dersimiz Var."
amac: ["bugün","python","dersimiz","var."] şeklinde çıktı veren kod yazınız.
"""

cumle = "Bugün Python Dersimiz Var."
cumle_liste = cumle.split() # cumle.split(i) olsaydı i'nin sağı ve solu olarak ayıracaktı.
print(cumle_liste)

['Bugün', 'Python', 'Dersimiz', 'Var.']


In [107]:
liste = []
for i in cumle_liste:
  kelime_kucuk_harf = i.lower()
  print(kelime_kucuk_harf)
  liste.append(kelime_kucuk_harf)
print(liste)

bugün
python
dersimiz
var.
['bugün', 'python', 'dersimiz', 'var.']


In [116]:
"""
problem: liste = [1,2,3,4,5,6]
fonksiyon
  girdi: liste
  çıktı: listedeki çift elemanların toplamı
"""

liste = [1,2,3,4,5,6]

def cift_eleman_toplami(liste):
  toplam = 0
  for i in liste:
    if i % 2 == 0:
      toplam = toplam + i
  return toplam
  print(toplam)

cift_eleman_toplami(liste)

12

while loop

In [117]:
i = 0
while(i < 4):
  print(i)
  i = i + 1

0
1
2
3


In [119]:
# while ile toplam
liste = [1,2,3,4,5,6]
toplam = 0
i = 0
while(i < len(liste)):
  toplam = toplam + liste[i]
  i = i + 1
print(toplam)

21


**Numpy**

In [120]:
import numpy as np

In [123]:
#numpy array oluştur
#liste = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
dizi = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(dizi)
print(type(dizi))

<class 'numpy.ndarray'>


In [124]:
# array boyutu
dizi.shape # (15,) -> 15x1'lik bir vektör

(15,)

In [125]:
# 15x1 lik bir array'i 3x5 lik bir matrise çevir
dizi2 = dizi.reshape(3,5)
print(dizi2)
print(dizi2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)


In [126]:
print("shape", dizi2.shape)
print("dimension", dizi2.ndim)
print("data type", dizi2.dtype.name)
print("size", dizi2.size)
print("type", type(dizi2))

shape (3, 5)
dimension 2
data type int64
size 15
type <class 'numpy.ndarray'>


In [127]:
dizi2D = np.array([[1,2,3,4], [5,6,7,8], [9,8,7,5]])
print(dizi2D)
print(dizi2D.shape)

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 5]]
(3, 4)


In [129]:
# sifirlardan oluşan bir array oluşturalim
sıfır_dizi = np.zeros((3,4))
sıfır_dizi

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [130]:
# birlerden olusan array
bir_dizi = np.ones((3,4))
bir_dizi

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [131]:
# bos bir array oluştur
bos_dizi = np.empty((2,4))
bos_dizi

array([[4.76894457e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [132]:
# arange(x,y,basamak) x den baslar y ye (y dahil degil) kadar gider basamak buyuklugunder artarak ilerler
# 10, 50, basamak = 5
dizi_aralik = np.arange(10,50,8)
dizi_aralik

array([10, 18, 26, 34, 42])

In [133]:
# linspace  (x,y,basamak) x ve y(dahil) araliginde basamak kadar sayiya boler
dizi_bosluk = np.linspace(10,50,103)
len(dizi_bosluk)

103

**Numpy Temel Operasyonlar**

In [134]:
import numpy as np

In [136]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [138]:
print("Toplama:",a+b)
print("Çıkarma:",a-b)
print("Kendi ile Çarpma:",a**2)

Toplama: [5 7 9]
Çıkarma: [-3 -3 -3]
Kendi ile Çarpma: [1 4 9]


In [139]:
#filtreleme
a = np.array([1,2,3])
filtre = a < 2 # a array'nin içerisinde bulunan 2 den küçük degerleri göster
filtre

array([ True, False, False])

In [140]:
# matris çarpımı
a = np.array([1,2,3])
b = np.array([4,5,6])
a.dot(b)

32

In [143]:
a = np.array([[1,2,3],[4,5,6]]) #2x3
b = np.array([[4,5,6],[1,2,3]]) #2x3 -> T -> 3x2
a.dot(b.T)

array([[32, 14],
       [77, 32]])

In [149]:
a = np.array([[1,2,3],
              [4,5,6]]) #2x3

print(a.sum())
print(np.sum(a))
print(a.max())
print(np.max(a))
print(a.min())
print(np.min(a))
print(a.mean())
print(np.mean(a))



print(a.sum(axis=0)) # sütun bazlı toplama
print(a.sum(axis=1)) # satır bazlı toplama

21
21
6
6
1
1
3.5
3.5
[5 7 9]
[ 6 15]


In [152]:
# karekök
print(np.sqrt(a))

# karesi
print(np.square(a))
print(a**2)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]


In [153]:
# rastgele sayi üretme
rasgele_dizi1 = np.random.random((3,3)) # normal dağılıma göre 0-1 arası rasgele dağılım
rasgele_dizi1

array([[0.05635841, 0.9632226 , 0.49736303],
       [0.469522  , 0.81243623, 0.95304434],
       [0.14864481, 0.43214976, 0.6965796 ]])

In [154]:
rastgele_dizi = np.random.normal(0 ,1 , 5) # normal dagilima 0 ortalamali 1 std, 5 adet deger uret
rastgele_dizi

array([-0.76070884, -0.4700101 ,  0.87732854, -0.38929505,  1.76109493])

**indeksleme ve slicing**

In [156]:
import numpy as np

In [159]:
dizi = np.array([1,2,3,4,5,6,7])
dizi[3]

4

In [161]:
dizi[0:4]

array([1, 2, 3, 4])

In [162]:
dizi[:4]

array([1, 2, 3, 4])

In [165]:
dizi[::-1] # tersine çevir

array([7, 6, 5, 4, 3, 2, 1])

In [166]:
dizi2D = np.array([[1,2,3,4,5], [6,7,8,9,10]])
dizi2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [169]:
dizi2D[1,1] # 2.satır 2.sütun

7

In [174]:
dizi2D[0,:]

array([1, 2, 3, 4, 5])

In [176]:
dizi2D[:,2]

array([3, 8])

In [180]:
dizi2D[:,2:4]

array([[3, 4],
       [8, 9]])

In [181]:
dizi2D[-1,2:4]

array([8, 9])

In [182]:
dizi2D[[0,1], [1,3]]

array([2, 9])

**shape manipulation**

In [183]:
import numpy as np

In [185]:
dizi2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
dizi2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [186]:
dizi2D_shape = dizi2D.shape
dizi2D_shape

(3, 3)

In [187]:
dizi2D.reshape(dizi2D_shape[0]*dizi2D_shape[1],1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [188]:
dizi2D.reshape(dizi2D_shape[0]*dizi2D_shape[1],-1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [189]:
dizi2D.ravel() # tek boyutlu hale getirir, tensorflow -> flattengg

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [190]:
dizi2D.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [191]:
print(dizi2D.reshape(dizi2D_shape[0]*dizi2D_shape[1],-1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [198]:
"""
1) A array = 2 boyutlu bir tane array -> (3,5)
2) B array = 1 boyutlu bir tane array -> (15,)
3) B array'ini (3,5) olacak sekilde reshape yapalim
4) C = A + B
5) D=linspace ve E=arange ile (3,5) lik matrisler olusturalim.
6) F = D + E
7) C'nin ve F'nin her bir elemanini for dongusu ile eleman eleman carpip G = (15,1) boyutunda elde edelim.
8) C ve F'yi (15,1) sonrasında C'nin ilk elemani ile F'nin son elemani toplayarak ilerleyelim.
9) toplam degerleri eger 1 den buyukse G1 isimli bir listeye atalim, else ise G2 isimli listeye atalim
"""
import numpy as np
# 2 boyutlu bir dizi oluşturma (3x5)
A = np.random.rand(3, 5)  # 0 ile 1 arasında rastgele sayılarla dolu 3x5'lik bir dizi
# 1 boyutlu bir dizi oluşturma (15 elemanlı)
B = np.arange(15)  # 0'dan 14'e kadar sayıları içeren bir dizi
# B dizisini 3x5 boyutunda yeniden şekillendirme
B = B.reshape(3, 5)
# A ve B dizilerini toplama
C = A + B
print("C: ",C)
D=np.linspace(10,50,15).reshape(3,5)
print("D: ",D)
E=np.arange(10,160,10).reshape(3,5)
print("E: ",E)
F=D+E
print("F: ",F)
G = []
for i in range(C.shape[0]):  # 3
    for j in range(C.shape[1]):  # 5
        G.append(C[i, j] * F[i, j])
print("G shape: ",np.array(G).shape)

C:  [[ 0.1977079   1.23930508  2.108394    3.62627513  4.80284366]
 [ 5.09384388  6.4996451   7.78264573  8.76105391  9.63255346]
 [10.73587382 11.37222279 12.70511079 13.4637681  14.51466128]]
D:  [[10.         12.85714286 15.71428571 18.57142857 21.42857143]
 [24.28571429 27.14285714 30.         32.85714286 35.71428571]
 [38.57142857 41.42857143 44.28571429 47.14285714 50.        ]]
E:  [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]
F:  [[ 20.          32.85714286  45.71428571  58.57142857  71.42857143]
 [ 84.28571429  97.14285714 110.         122.85714286 135.71428571]
 [148.57142857 161.42857143 174.28571429 187.14285714 200.        ]]
G shape:  (15,)


In [199]:
"""
[1,2,3]

[4,5,6]
7,7,7
"""
C = C.reshape(15,1)
F = F.reshape(15,1)
F =F[::-1]
G1 = []
G2 = []
for i in range(len(C)):
    toplam = C[i] + F[i]
    if toplam > 1:
        G1.append(toplam)
    else:
        G2.append(toplam)
print(G1,G2)

[array([200.1977079]), array([188.38216222]), array([176.39410828]), array([165.05484656]), array([153.37427223]), array([140.80812959]), array([129.35678796]), array([117.78264573]), array([105.90391105]), array([93.91826775]), array([82.16444525]), array([69.94365136]), array([58.41939651]), array([46.32091096]), array([34.51466128])] []


In [200]:
C_flat = C.reshape(-1, 1)  # -1 otomatik olarak 15 elemanı kullanır
F_flat = F.reshape(-1, 1)

# G1 ve G2 listelerini tanımlama
G1 = []
G2 = []

# C'nin ilk elemanı ve F'nin son elemanı toplama işlemi ile ilerleme
for i in range(len(C_flat)):  # C_flat'in uzunluğunu kullanarak döngüyü oluştur
    toplam = C_flat[i, 0] + F_flat[len(F_flat) - 1 - i, 0]  # len kullanarak sondan eleman al
    if toplam > 1:
        G1.append(toplam)
    else:
        G2.append(toplam)
# Sonuçları yazdırma
print("G1 (Toplam > 1 olanlar):", G1)
print("G2 (Toplam <= 1 olanlar):", G2)

G1 (Toplam > 1 olanlar): [20.19770790166806, 34.09644793346444, 47.82267971109872, 62.19770369982412, 76.23141508692137, 89.37955816085537, 103.64250224466797, 117.78264572513403, 131.6181967661664, 145.34683917458733, 159.30730239428186, 172.80079421665386, 186.99082508054977, 200.6066252416273, 214.5146612760255]
G2 (Toplam <= 1 olanlar): []
